### ISSUE TITLE
Logs don't have [level] [category]

### ISSUE THREAD

**Issue by timkelty** [nerds-and-company/loghelper#3]
I've started sending logs to syslog so I can use Papertrail.
I've noticed that they don't have the [level] [category] prefix that FileLogRoute does.

The category seems especially helpful for filtering out things like: `[exception.Craft\HttpException.404]`.

Would you consider a PR with this added?

**Comment by boboldehampsink** [comment]
Sure!

**Comment by boboldehampsink** [comment]
Fixed with #5
